[workspace]
resolver = "2"

members = ["backend", "frontend/src-tauri"]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
collapsible_if = "warn"
collapsible_else_if = "warn"
collapsible_match = "warn"
collapsible_str_replace = "warn"
expect_used = "deny"
inconsistent_struct_constructor = "allow"
indexing_slicing = "deny"
missing_errors_doc = "allow"
must_use_candidate = "allow"
panic = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
unused_doc_comments = "allow"
unsafe_code = "deny"
