[package]
name = "backend"
version = "0.0.1"
authors = ["Alex Kovalov <alexkovalevkpi@gmail.com>"]

edition = "2024"
rust-version = "1.98"

categories = ["science"]

readme = "../README.md"
license = "MIT"
repository = "https://github.com/xairaven/xPlagiarismChecker"

[lints]
workspace = true

[dependencies]
compress-tools = "0.16.1"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strum = "0.28.0"
strum_macros = "0.28.0"
thiserror = "2.0.20"
uuid = { version = "1.25.0", features = ["v4"] }
walkdir = "2.5.0"
zip = "9.0.0-pre3"
